# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
# Use the official Node.js image as the base image
FROM node:22.12-alpine AS builder

# Set the working directory
WORKDIR /app

# Copy the package.json and package-lock.json files
COPY package.json package-lock.json ./

# Install dependencies
RUN npm install

# Copy the source code
COPY src/ ./src/
COPY tsconfig.json ./

# Build the TypeScript code
RUN npm run build

# Use a smaller image to run the application
FROM node:22.12-alpine AS release

# Set the working directory
WORKDIR /app

# Copy only the necessary files from the builder stage
COPY --from=builder /app/dist ./dist
COPY --from=builder /app/package.json ./package.json

# Set environment variables (update these with actual values)
ENV GENTORO_API_KEY=<your_api_key>
ENV GENTORO_BRIDGE_UID=<your_bridge_uid>
ENV GENTORO_BASE_URL=<url_where_gentoro_is_hosted>

# Run the server
ENTRYPOINT ["node", "dist/index.js"]